name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Download ffplay
      run: wget https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v4.2.1/ffplay-4.2.1-osx-64.zip
    
    - name: Unzip ffplay
      run: unzip ./ffplay-4.2.1-osx-64.zip
      
    - name: Copy ffplay binary to /usr/local/bin
      run: cp ./ffplay /usr/local/bin/ffplay
      
    - name: Cache OpenCV
      id: opencv-cache
      uses: actions/cache@v2
      with:
        path: ./opencv-install
        key: ${{ runner.os }}-opencv-cache

    - name: Install OpenCV
      uses: rayandrews/with-opencv-action@v1
      with:  
        dir: ./opencv-install
        cached: ${{ steps.opencv-cache.outputs.cache-hit }}
        opencv-version: '4.0.0'
      
    - name: Xcode Build
      uses: devbotsxyz/xcode-build@v1.0.0
      with:
        project: ./c++/video-to-ascii/video-to-ascii.xcodeproj
