name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Install ffmpeg
      run: brew install ffmpeg
    
    - name: Xcode Build
      uses: devbotsxyz/xcode-build@v1.0.0
      with:
        project: /c++/video-to-ascii/video-to-ascii.xcodeproj
